version: '3.3'

services:
  flashcard:
    build: .
    ports:
      - 9001:9001
    environment:
      PORT: 9001
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
