import Document, { Html, Head, Main, NextScript, DocumentContext } from "next/document";
import { ColorModeScript } from '@chakra-ui/react'
import {themeConfig} from 'styles/theme'

class MyDocument extends Document {
  static async getInitialProps(ctx: DocumentContext) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
      <Head>
        <meta name="recall" content="Generated by create next app" />
      </Head>
        <body>
          {/* 👇 For chakra dark mode local storage syncing */}
          <ColorModeScript initialColorMode={themeConfig.initialColorMode} />
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
